### ISSUE TITLE
Errors on installation 

### ISSUE THREAD

**Issue by andrewczgithub** [slinderman/ssm#54] opened 2019-08-01 05:34 UTC
Hi @slinderman 
apologies i am getting errors on the install 

Requirement already satisfied: six in /home/andrewcz/miniconda3/envs/myenv1/lib/python3.7/site-packages (from cycler>=0.10->matplotlib->ssm==0.0.1) (1.12.0)
Installing collected packages: ssm
  Running setup.py develop for ssm
    ERROR: Complete output from command /home/andrewcz/miniconda3/envs/myenv1/bin/python -c 'import setuptools, tokenize;__file__='"'"'/home/andrewcz/ssm/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps:                                 
    ERROR: USE_OPENMP False
    running develop                                                                                                                                                                           
    running egg_info                                                                                                                                                                          
    writing ssm.egg-info/PKG-INFO                                                                                                                                                             
    writing dependency_links to ssm.egg-info/dependency_links.txt                                                                                                                             
    writing requirements to ssm.egg-info/requires.txt                                                                                                                                         
    writing top-level names to ssm.egg-info/top_level.txt                                                                                                                                     
    reading manifest file 'ssm.egg-info/SOURCES.txt'                                                                                                                                          
    writing manifest file 'ssm.egg-info/SOURCES.txt'                                                                                                                                          
    running build_ext                                                                                                                                                                         
    building 'ssm.messages' extension                                                                                                                                                         
    gcc -pthread -B /home/andrewcz/miniconda3/envs/myenv1/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/andrewcz/.local/lib/python3.7/site-packages/numpy/core/include -I/home/andrewcz/miniconda3/envs/myenv1/include/python3.7m -I/home/andrewcz/miniconda3/envs/myenv1/include/python3.7m -c ssm/messages.cpp -o build/temp.linux-x86_64-3.7/ssm/messages.o -O3                                                                                                                                                       
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++                                                                                           
    In file included from /home/andrewcz/.local/lib/python3.7/site-packages/numpy/core/include/numpy/ndarraytypes.h:1822,                                                                     
                     from /home/andrewcz/.local/lib/python3.7/site-packages/numpy/core/include/numpy/ndarrayobject.h:12,                                                                      
                     from /home/andrewcz/.local/lib/python3.7/site-packages/numpy/core/include/numpy/arrayobject.h:4,                                                                         
                     from ssm/messages.cpp:629:                                                                                                                                               
    /home/andrewcz/.local/lib/python3.7/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:17:2: warning: #warning "Using deprecated NumPy API, disable it with " "#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]                                                                                                                                                  
       17 | #warning "Using deprecated NumPy API, disable it with " \                                                                                                                         
          |  ^~~~~~~                                                                                                                                                                          
    g++ -pthread -shared -B /home/andrewcz/miniconda3/envs/myenv1/compiler_compat -L/home/andrewcz/miniconda3/envs/myenv1/lib -Wl,-rpath=/home/andrewcz/miniconda3/envs/myenv1/lib -Wl,--no-as-needed -Wl,--sysroot=/ build/temp.linux-x86_64-3.7/ssm/messages.o -o build/lib.linux-x86_64-3.7/ssm/messages.cpython-37m-x86_64-linux-gnu.so                                                 
    /home/andrewcz/miniconda3/envs/myenv1/compiler_compat/ld: build/temp.linux-x86_64-3.7/ssm/messages.o: unable to initialize decompress status for section .debug_info                      
    /home/andrewcz/miniconda3/envs/myenv1/compiler_compat/ld: build/temp.linux-x86_64-3.7/ssm/messages.o: unable to initialize decompress status for section .debug_info                      
    /home/andrewcz/miniconda3/envs/myenv1/compiler_compat/ld: build/temp.linux-x86_64-3.7/ssm/messages.o: unable to initialize decompress status for section .debug_info                      
    /home/andrewcz/miniconda3/envs/myenv1/compiler_compat/ld: build/temp.linux-x86_64-3.7/ssm/messages.o: unable to initialize decompress status for section .debug_info                      
    build/temp.linux-x86_64-3.7/ssm/messages.o: file not recognized: file format not recognized                                                                                               
    collect2: error: ld returned 1 exit status                                                                                                                                                
    error: command 'g++' failed with exit status 1                                                                                                                                            
    ----------------------------------------                                                                                                                                                  
ERROR: Command "/home/andrewcz/miniconda3/envs/myenv1/bin/python -c 'import setuptools, tokenize;__file__='"'"'/home/andrewcz/ssm/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps" failed with error code 1 in /home/andrewcz/ssm/

**Comment by slinderman** [comment] 2019-08-09 01:10
Hi Andrew,

I'm not sure what's going on here.  It looks like the Travis builds are working on Linux.  For comparison, here is the relevant section of the Travis output:
```
    gcc -pthread -B /home/travis/miniconda/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/travis/miniconda/lib/python3.6/site-packages/numpy/core/include -I/home/travis/miniconda/include/python3.6m -I/home/travis/miniconda/include/python3.6m -c ssm/messages.cpp -o build/temp.linux-x86_64-3.6/ssm/messages.o -O3
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
    In file included from /home/travis/miniconda/lib/python3.6/site-packages/numpy/core/include/numpy/ndarraytypes.h:1830:0,
                     from /home/travis/miniconda/lib/python3.6/site-packages/numpy/core/include/numpy/ndarrayobject.h:12,
                     from /home/travis/miniconda/lib/python3.6/site-packages/numpy/core/include/numpy/arrayobject.h:4,
                     from ssm/messages.cpp:629:
    /home/travis/miniconda/lib/python3.6/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:17:2: warning: #warning "Using deprecated NumPy API, disable it with " "#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
     #warning "Using deprecated NumPy API, disable it with " \
      ^
    creating build/lib.linux-x86_64-3.6
    creating build/lib.linux-x86_64-3.6/ssm
    g++ -pthread -shared -B /home/travis/miniconda/compiler_compat -L/home/travis/miniconda/lib -Wl,-rpath=/home/travis/miniconda/lib -Wl,--no-as-needed -Wl,--sysroot=/ build/temp.linux-x86_64-3.6/ssm/messages.o -o build/lib.linux-x86_64-3.6/ssm/messages.cpython-36m-x86_64-linux-gnu.so
```
It looks pretty similar to me... I wonder if it's a problem with your gcc/g++ config?   Perhaps you could try installing from the `ssm` directory with `pip install -v -e .`  and see if it shows any more information?

**Comment by slinderman** [comment] 2019-10-15 00:36
I'm going to close this issue as it doesn't seem to have been reproduced by others.  Please reopen if you continue to run into trouble!

**Closed by slinderman** 2019-10-15 00:36 UTC

**Comment by im-Kitsch** [comment] 2019-10-16 09:26
> Hi @slinderman
> apologies i am getting errors on the install
> 
> Requirement already satisfied: six in /home/andrewcz/miniconda3/envs/myenv1/lib/python3.7/site-packages (from cycler>=0.10->matplotlib->ssm==0.0.1) (1.12.0)
> Installing collected packages: ssm
> Running setup.py develop for ssm
> ERROR: Complete output from command /home/andrewcz/miniconda3/envs/myenv1/bin/python -c 'import setuptools, tokenize;**file**='"'"'/home/andrewcz/ssm/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(**file**);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, **file**, '"'"'exec'"'"'))' develop --no-deps:
> ERROR: USE_OPENMP False
> running develop
> running egg_info
> writing ssm.egg-info/PKG-INFO
> writing dependency_links to ssm.egg-info/dependency_links.txt
> writing requirements to ssm.egg-info/requires.txt
> writing top-level names to ssm.egg-info/top_level.txt
> reading manifest file 'ssm.egg-info/SOURCES.txt'
> writing manifest file 'ssm.egg-info/SOURCES.txt'
> running build_ext
> building 'ssm.messages' extension
> gcc -pthread -B /home/andrewcz/miniconda3/envs/myenv1/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/andrewcz/.local/lib/python3.7/site-packages/numpy/core/include -I/home/andrewcz/miniconda3/envs/myenv1/include/python3.7m -I/home/andrewcz/miniconda3/envs/myenv1/include/python3.7m -c ssm/messages.cpp -o build/temp.linux-x86_64-3.7/ssm/messages.o -O3
> cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
> In file included from /home/andrewcz/.local/lib/python3.7/site-packages/numpy/core/include/numpy/ndarraytypes.h:1822,
> from /home/andrewcz/.local/lib/python3.7/site-packages/numpy/core/include/numpy/ndarrayobject.h:12,
> from /home/andrewcz/.local/lib/python3.7/site-packages/numpy/core/include/numpy/arrayobject.h:4,
> from ssm/messages.cpp:629:
> /home/andrewcz/.local/lib/python3.7/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:17:2: warning: #warning "Using deprecated NumPy API, disable it with " "#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
> 17 | #warning "Using deprecated NumPy API, disable it with " \
> | ^~~~~~~
> g++ -pthread -shared -B /home/andrewcz/miniconda3/envs/myenv1/compiler_compat -L/home/andrewcz/miniconda3/envs/myenv1/lib -Wl,-rpath=/home/andrewcz/miniconda3/envs/myenv1/lib -Wl,--no-as-needed -Wl,--sysroot=/ build/temp.linux-x86_64-3.7/ssm/messages.o -o build/lib.linux-x86_64-3.7/ssm/messages.cpython-37m-x86_64-linux-gnu.so
> /home/andrewcz/miniconda3/envs/myenv1/compiler_compat/ld: build/temp.linux-x86_64-3.7/ssm/messages.o: unable to initialize decompress status for section .debug_info
> /home/andrewcz/miniconda3/envs/myenv1/compiler_compat/ld: build/temp.linux-x86_64-3.7/ssm/messages.o: unable to initialize decompress status for section .debug_info
> /home/andrewcz/miniconda3/envs/myenv1/compiler_compat/ld: build/temp.linux-x86_64-3.7/ssm/messages.o: unable to initialize decompress status for section .debug_info
> /home/andrewcz/miniconda3/envs/myenv1/compiler_compat/ld: build/temp.linux-x86_64-3.7/ssm/messages.o: unable to initialize decompress status for section .debug_info
> build/temp.linux-x86_64-3.7/ssm/messages.o: file not recognized: file format not recognized
> collect2: error: ld returned 1 exit status
> error: command 'g++' failed with exit status 1
> ----------------------------------------
> ERROR: Command "/home/andrewcz/miniconda3/envs/myenv1/bin/python -c 'import setuptools, tokenize;**file**='"'"'/home/andrewcz/ssm/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(**file**);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, **file**, '"'"'exec'"'"'))' develop --no-deps" failed with error code 1 in /home/andrewcz/ssm/

For me I have the same issue but followed by [this issue ](https://github.com/slinderman/ssm/issues/54)I have solved it.

I do 
export CC=$(which gcc-9) 
export CXX=$(which g++-9)
